// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiContribuyente;

#nullable disable

namespace WebApiContribuyente.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220214210746_Declaraciones")]
    partial class Declaraciones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiContribuyente.Entidades.Contribuyente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contribuyentes");
                });

            modelBuilder.Entity("WebApiContribuyente.Entidades.Declaracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ContribuyenteId")
                        .HasColumnType("int");

                    b.Property<string>("Mes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContribuyenteId");

                    b.ToTable("Declaciones");
                });

            modelBuilder.Entity("WebApiContribuyente.Entidades.Declaracion", b =>
                {
                    b.HasOne("WebApiContribuyente.Entidades.Contribuyente", "Contribuyente")
                        .WithMany("Declaraciones")
                        .HasForeignKey("ContribuyenteId");

                    b.Navigation("Contribuyente");
                });

            modelBuilder.Entity("WebApiContribuyente.Entidades.Contribuyente", b =>
                {
                    b.Navigation("Declaraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
